### ISSUE TITLE
Won't work with GATE 8

### ISSUE THREAD

**Issue by maxott** [SemanticSoftwareLab/Supplements-ScholarLens#1]
Hi,

I was trying to install the pipeline with the current version of GATE, but I get all kinds of errors. One issue is that the interface for the plugin manager has changed. There is no longer an 'add repository' and besides, what is the 'Semantic Software Lab repository' anyway.

Thanks

**Comment by rene-w** [comment]
Our GATE tools/pipelines have not yet been updated to work with the new format introduced in GATE v8.5. The simplest solution if you want to run them as-is would be to use GATE v8.4.1.

At one point we will update them to the new format, but I am afraid there is no specific timeline for this. If you want to try updating them yourself, you can check the GATE developer documentation under https://gate.ac.uk/sale/tao/splitch3.html#x6-580003.9.5
